docker contaienr for dedi

diff --git a/CringeBootstrap/Properties/AppRun b/CringeBootstrap/Properties/AppRun
--- a/CringeBootstrap/Properties/AppRun
+++ b/CringeBootstrap/Properties/AppRun
@@ -31,10 +31,18 @@ if [ "$_dedicated" -eq 1 ]; then
   export DOTNET_USERDEV_RUNDIR="$(realpath "$_instance")"
 
   echo "Downloading game files via DepotDownloader..."
-  dotnet "$this_dir"/usr/share/DepotDownloader/DepotDownloader.dll -app 298740 -depot 298741 -os windows -dir game || {
+  dotnet "$this_dir"/usr/share/DepotDownloader/DepotDownloader.dll -app 298740 -depot 298741 -dir game -max-downloads "$(nproc)" || {
     echo "Error: DepotDownloader failed." >&2
     exit 1
   }
+  
+  echo "Downloading steamclient files via DepotDownloader..."
+  dotnet "$this_dir"/usr/share/DepotDownloader/DepotDownloader.dll -app 1007 -depot 1006 -dir game -max-downloads "$(nproc)" || {
+    echo "Error: DepotDownloader steamclient failed." >&2
+    exit 1
+  }
+  
+  export LD_LIBRARY_PATH="$(realpath "./game/linux64")":"$LD_LIBRARY_PATH"
   
   mkdir -p "$DOTNET_USERDEV_RUNDIR/SpaceEngineers/Saves/World"
 
